import json
import os

from investopedia_api import InvestopediaApi


def load_auth():
    if os.path.exists("credentials.json"):
        with open("credentials.json", "r", encoding="utf-8") as auth_file:
            return json.load(auth_file)

    # You may instead use INVESTOPEDIA_ACCESS_TOKEN / INVESTOPEDIA_REFRESH_TOKEN
    # or an existing auth.json generated by auth.js.
    return None


auth = load_auth()

# Optional exact game name. Leave unset to use Investopedia's first active game.
game_name = os.environ.get("INVESTOPEDIA_GAME_NAME")
client = InvestopediaApi(auth, game_name=game_name)

print("\nAvailable active games:")
for portfolio in client.portfolios:
    selected = "*" if portfolio.portfolio_id == client.portfolio.portfolio_id else " "
    print(
        "%s %s | game_id=%s | portfolio_id=%s"
        % (
            selected,
            portfolio.game_name,
            portfolio.game_id,
            portfolio.portfolio_id,
        )
    )

p = client.portfolio
print("\nSelected portfolio")
print("------------------")
print("Game:", p.game_name)
print("Portfolio ID:", p.portfolio_id)
print("Portfolio Value:", p.account_value)
print("Cash:", p.cash)
print("Buying Power:", p.buying_power)
print("Annual Return Percent:", p.annual_return_pct)

print("\nOpen orders:")
for order in p.open_orders:
    print(
        "%s | %s | qty=%s | price=%s"
        % (
            order.trade_type,
            order.symbol,
            order.quantity,
            order.order_price,
        )
    )

print("\nLong positions:")
for position in p.stock_portfolio:
    print(
        "%s | qty=%s | purchase=%s | value=%s"
        % (
            position.symbol,
            position.quantity,
            position.purchase_price,
            position.market_value,
        )
    )

# Trading example (intentionally NOT executed automatically):
#
# from investopedia_api import StockTrade, TransactionType
#
# trade = StockTrade(
#     portfolio_id=p.portfolio_id,
#     symbol="AAPL",
#     quantity=1,
#     transaction_type=TransactionType.BUY,
# )
# trade.validate()
# trade.execute()
